/* eslint-disable */

const movies = {
	data: [
		{
			'NearestCinemaCount': 149,
			'NearestDay': 1510300800,
			'NearestShowtimeCount': 1711,
	'aN1': '肯尼思·布拉纳',
	'aN2': '约翰尼·德普',
	'actors': '肯尼思·布拉纳 / 约翰尼·德普 / 米歇尔·菲佛 / 黛茜·雷德利',
	'cC': 149,
	'commonSpecial': '大侦探波洛遇上列车血案疑云重重',
	'd': '114',
	'dN': '肯尼思·布拉纳',
	'def': 0,
	'id': 225829,
	'img': 'http://img5.mtime.cn/mt/2017/11/07/164403.84902974_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': true,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': true,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': true,
	'isTicket': true,
	'm': '',
	'movieType': '犯罪 / 剧情 / 悬疑',
	'p': [
			'犯罪剧情悬疑'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '20171110',
	'rsC': 0,
	'sC': 3225,
	't': '东方快车谋杀案',
	'tCn': '东方快车谋杀案',
	'tEn': 'Murder on the Orient Express',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			},
			{
					'enum': 6,
					'version': '中国巨幕'
			}
	],
	'wantedCount': 2906
},
{
	'NearestCinemaCount': 153,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 1230,
	'aN1': '张晋',
	'aN2': '余文乐',
	'actors': '张晋 / 余文乐 / 文咏珊 / 吴樾',
	'cC': 153,
	'commonSpecial': '张晋余文乐吴樾对战厮杀',
	'd': '100',
	'dN': '李子俊',
	'def': 0,
	'id': 232577,
	'img': 'http://img5.mtime.cn/mt/2017/10/13/101534.23587435_1280X720X2.jpg',
	'is3D': true,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': true,
	'isTicket': true,
	'm': '',
	'movieType': '动作 / 剧情 / 犯罪',
	'p': [
			'动作剧情犯罪'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '20171110',
	'rsC': 0,
	'sC': 2048,
	't': '狂兽',
	'tCn': '狂兽',
	'tEn': 'The Brink',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			},
			{
					'enum': 2,
					'version': '3D'
			}
	],
	'wantedCount': 938
},
{
	'NearestCinemaCount': 131,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 556,
	'aN1': '刘亦菲',
	'aN2': '埃米尔·赫斯基',
	'actors': '刘亦菲 / 埃米尔·赫斯基 / 严屹宽 / 余少群',
	'cC': 134,
	'commonSpecial': '浙江军民竭力营救美国飞行员',
	'd': '97',
	'dN': '比利·奥古斯特',
	'def': 0,
	'id': 229447,
	'img': 'http://img5.mtime.cn/mt/2017/11/06/104450.51823014_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': true,
	'isTicket': true,
	'm': '',
	'movieType': '爱情 / 剧情 / 战争',
	'p': [
			'爱情剧情战争'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '20171110',
	'rsC': 0,
	'sC': 830,
	't': '烽火芳菲',
	'tCn': '烽火芳菲',
	'tEn': 'The Chinese Widow',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 272
},
{
	'NearestCinemaCount': 132,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 524,
	'aN1': '高晓攀',
	'aN2': '尤宪超',
	'actors': '高晓攀 / 尤宪超 / 于莎莎 / 李璨琛',
	'cC': 132,
	'commonSpecial': '高晓攀率嘻哈包袱铺疯狂捣蛋',
	'd': '90',
	'dN': '高晓攀',
	'def': 0,
	'id': 235551,
	'img': 'http://img5.mtime.cn/mt/2017/11/02/165618.69673712_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': true,
	'isTicket': true,
	'm': '',
	'movieType': '喜剧',
	'p': [
			'喜剧'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '20171110',
	'rsC': 0,
	'sC': 724,
	't': '兄弟，别闹！',
	'tCn': '兄弟，别闹！',
	'tEn': 'Trouble Makers',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 201
},
{
	'NearestCinemaCount': 130,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 394,
	'aN1': '周渝民',
	'aN2': '薛凯琪',
	'actors': '周渝民 / 薛凯琪 / 郑中基 / 恬妞',
	'cC': 131,
	'commonSpecial': '神算冤家周渝民薛凯琪相爱相杀',
	'd': '99',
	'dN': '谷德昭',
	'def': 0,
	'id': 234491,
	'img': 'http://img5.mtime.cn/mt/2017/11/02/120621.73045739_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': true,
	'isTicket': true,
	'm': '',
	'movieType': '爱情 / 喜剧',
	'p': [
			'爱情喜剧'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '20171110',
	'rsC': 0,
	'sC': 577,
	't': '天生不对',
	'tCn': '天生不对',
	'tEn': 'Perfect Couple',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 508
},
{
	'NearestCinemaCount': 33,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 50,
	'aN1': '孙博',
	'aN2': '李昊泽',
	'actors': '孙博 / 李昊泽 / 王继贤 / 刘雪涛',
	'cC': 34,
	'commonSpecial': '',
	'd': '90',
	'dN': '宋灏霖',
	'def': 0,
	'id': 237613,
	'img': 'http://img5.mtime.cn/mt/2017/10/26/230739.28154846_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': true,
	'isTicket': true,
	'm': '',
	'movieType': '剧情 / 喜剧',
	'p': [
			'剧情喜剧'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '20171110',
	'rsC': 0,
	'sC': 62,
	't': '猪太狼的夏天',
	'tCn': '猪太狼的夏天',
	'tEn': "Mr. Zhu's Summer",
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 31
},
{
	'NearestCinemaCount': 148,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 1485,
	'aN1': '克里斯·海姆斯沃斯',
	'aN2': '凯特·布兰切特',
	'actors': '克里斯·海姆斯沃斯 / 凯特·布兰切特 / 汤姆·希德勒斯顿 / 马克·鲁法洛',
	'cC': 148,
	'commonSpecial': '超级英雄界的“开心麻花”电影',
	'd': '130',
	'dN': '塔伊加·维迪提',
	'def': 0,
	'id': 209123,
	'img': 'http://img5.mtime.cn/mt/2017/09/28/154742.20554008_1280X720X2.jpg',
	'is3D': true,
	'isDMAX': true,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': true,
	'isIMAX': false,
	'isIMAX3D': true,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '动作 / 冒险 / 喜剧',
	'p': [
			'动作冒险喜剧'
	],
	'preferentialFlag': false,
	'r': 7.8,
	'rc': 0,
	'rd': '20171103',
	'rsC': 0,
	'sC': 2825,
	't': '雷神3：诸神黄昏',
	'tCn': '雷神3：诸神黄昏',
	'tEn': 'Thor: Ragnarok',
	'ua': -1,
	'versions': [
			{
					'enum': 2,
					'version': '3D'
			},
			{
					'enum': 4,
					'version': 'IMAX3D'
			},
			{
					'enum': 6,
					'version': '中国巨幕'
			}
	],
	'wantedCount': 10322
},
{
	'NearestCinemaCount': 60,
	'NearestDay': 1510819200,
	'NearestShowtimeCount': 71,
	'aN1': '本·阿弗莱克',
	'aN2': '盖尔·加朵',
	'actors': '本·阿弗莱克 / 盖尔·加朵 / 杰森·莫玛 / 埃兹拉·米勒',
	'cC': 74,
	'commonSpecial': '',
	'd': '120',
	'dN': '扎克·施奈德',
	'def': 0,
	'id': 70233,
	'img': 'http://img5.mtime.cn/mt/2017/10/11/103057.81077836_1280X720X2.jpg',
	'is3D': true,
	'isDMAX': true,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': true,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '动作 / 冒险 / 奇幻',
	'p': [
			'动作冒险奇幻'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '20171117',
	'rsC': 0,
	'sC': 998,
	't': '正义联盟',
	'tCn': '正义联盟',
	'tEn': 'Justice League',
	'ua': -1,
	'versions': [
			{
					'enum': 2,
					'version': '3D'
			},
			{
					'enum': 4,
					'version': 'IMAX3D'
			},
			{
					'enum': 6,
					'version': '中国巨幕'
			}
	],
	'wantedCount': 12126
},
{
	'NearestCinemaCount': 90,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 277,
	'aN1': '赵汉唐',
	'aN2': '江一燕',
	'actors': '赵汉唐 / 江一燕 / 赵汉唐 / 赵汉唐',
	'cC': 108,
	'commonSpecial': '徒步穿越 “生命禁区——极地羌塘”',
	'd': '110',
	'dN': '赵汉唐',
	'def': 0,
	'id': 244235,
	'img': 'http://img5.mtime.cn/mt/2017/10/26/151523.80306138_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '剧情 / 冒险',
	'p': [
			'剧情冒险'
	],
	'preferentialFlag': false,
	'r': 7,
	'rc': 0,
	'rd': '20171103',
	'rsC': 0,
	'sC': 512,
	't': '七十七天',
	'tCn': '七十七天',
	'tEn': 'Seventy-Seven Days',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 857
},
{
	'NearestCinemaCount': 96,
	'NearestDay': 1510387200,
	'NearestShowtimeCount': 344,
	'aN1': '松本梨香',
	'aN2': '大谷育江',
	'actors': '松本梨香 / 大谷育江 / 市川染五郎 / 寺崎裕香',
	'cC': 96,
	'commonSpecial': '',
	'd': '90',
	'dN': '汤山邦彦',
	'def': 0,
	'id': 238232,
	'img': 'http://img5.mtime.cn/mt/2017/10/25/093028.15916728_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '动画 / 奇幻 / 冒险',
	'p': [
			'动画奇幻冒险'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '20171111',
	'rsC': 0,
	'sC': 493,
	't': '精灵宝可梦：波尔凯尼恩与机巧的玛机雅娜',
	'tCn': '精灵宝可梦：波尔凯尼恩与机巧的玛机雅娜',
	'tEn': 'Pokémon the Movie XY&Z: Volcanion and the Ingenious Magearna',
	'ua': -1,
	'versions': [],
	'wantedCount': 328
},
{
	'NearestCinemaCount': 63,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 159,
	'aN1': '杰拉德·巴特勒',
	'aN2': '吉姆·斯特吉斯',
	'actors': '杰拉德·巴特勒 / 吉姆·斯特吉斯 / 艾比·考尼什 / 艾德·哈里斯',
	'cC': 74,
	'commonSpecial': '天灾远不如人祸可怕',
	'd': '109',
	'dN': '迪安·德夫林',
	'def': 0,
	'id': 211978,
	'img': 'http://img5.mtime.cn/mt/2017/09/25/110306.70024470_1280X720X2.jpg',
	'is3D': true,
	'isDMAX': true,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': true,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '动作 / 科幻 / 惊悚',
	'p': [
			'动作科幻惊悚'
	],
	'preferentialFlag': false,
	'r': 6.5,
	'rc': 0,
	'rd': '20171027',
	'rsC': 0,
	'sC': 261,
	't': '全球风暴',
	'tCn': '全球风暴',
	'tEn': 'Geostorm',
	'ua': -1,
	'versions': [
			{
					'enum': 2,
					'version': '3D'
			},
			{
					'enum': 4,
					'version': 'IMAX3D'
			},
			{
					'enum': 6,
					'version': '中国巨幕'
			}
	],
	'wantedCount': 2560
},
{
	'NearestCinemaCount': 39,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 89,
	'aN1': '艾伦',
	'aN2': '马丽',
	'actors': '艾伦 / 马丽 / 沈腾 / 田雨',
	'cC': 43,
	'commonSpecial': '艾伦马丽互换身体引发爆笑故事',
	'd': '100',
	'dN': '宋阳',
	'def': 0,
	'id': 246526,
	'img': 'http://img5.mtime.cn/mt/2017/09/13/103357.41321546_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': true,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': true,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '喜剧',
	'p': [
			'喜剧'
	],
	'preferentialFlag': false,
	'r': 7.4,
	'rc': 0,
	'rd': '20170930',
	'rsC': 0,
	'sC': 170,
	't': '羞羞的铁拳',
	'tCn': '羞羞的铁拳',
	'tEn': 'Never Say Die',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			},
			{
					'enum': 3,
					'version': 'IMAX'
			},
			{
					'enum': 6,
					'version': '中国巨幕'
			}
	],
	'wantedCount': 4363
},
{
	'NearestCinemaCount': 37,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 77,
	'aN1': '塔伦·埃格顿',
	'aN2': '科林·费斯',
	'actors': '塔伦·埃格顿 / 科林·费斯 / 马克·斯特朗 / 朱丽安·摩尔',
	'cC': 45,
	'commonSpecial': '英美特工奇招大战\'病娇\'反派',
	'd': '141',
	'dN': '马修·沃恩',
	'def': 0,
	'id': 224428,
	'img': 'http://img5.mtime.cn/mt/2017/09/25/110015.92324441_1280X720X2.jpg',
	'is3D': true,
	'isDMAX': true,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': true,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '动作 / 冒险 / 喜剧',
	'p': [
			'动作冒险喜剧'
	],
	'preferentialFlag': false,
	'r': 7.5,
	'rc': 0,
	'rd': '20171020',
	'rsC': 0,
	'sC': 146,
	't': '王牌特工2：黄金圈',
	'tCn': '王牌特工2：黄金圈',
	'tEn': 'Kingsman: The Golden Circle',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			},
			{
					'enum': 2,
					'version': '3D'
			},
			{
					'enum': 4,
					'version': 'IMAX3D'
			},
			{
					'enum': 6,
					'version': '中国巨幕'
			}
	],
	'wantedCount': 7749
},
{
	'NearestCinemaCount': 35,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 70,
	'aN1': '张艾嘉',
	'aN2': '田壮壮',
	'actors': '张艾嘉 / 田壮壮 / 郎月婷 / 宋宁峰',
	'cC': 39,
	'commonSpecial': '张艾嘉聚焦三代女人情感故事',
	'd': '121',
	'dN': '张艾嘉',
	'def': 0,
	'id': 233498,
	'img': 'http://img5.mtime.cn/mt/2017/10/17/210424.21162503_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '爱情 / 剧情',
	'p': [
			'爱情剧情'
	],
	'preferentialFlag': false,
	'r': 8.4,
	'rc': 0,
	'rd': '20171103',
	'rsC': 0,
	'sC': 141,
	't': '相爱相亲',
	'tCn': '相爱相亲',
	'tEn': 'Love Education',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 469
},
{
	'NearestCinemaCount': 35,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 71,
	'aN1': '郭富城',
	'aN2': '赵丽颖',
	'actors': '郭富城 / 赵丽颖 / 张翰 / 任达华',
	'cC': 40,
	'commonSpecial': '郭富城赵丽颖组革命CP',
	'd': '100',
	'dN': '钟少雄',
	'def': 0,
	'id': 220789,
	'img': 'http://img5.mtime.cn/mt/2017/09/14/095059.93910928_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '战争 / 动作 / 剧情',
	'p': [
			'战争动作剧情'
	],
	'preferentialFlag': false,
	'r': 5.8,
	'rc': 0,
	'rd': '20171103',
	'rsC': 0,
	'sC': 136,
	't': '密战',
	'tCn': '密战',
	'tEn': 'Eternal Wave',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 3012
},
{
	'NearestCinemaCount': 27,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 54,
	'aN1': '瑞恩·高斯林',
	'aN2': '哈里森·福特',
	'actors': '瑞恩·高斯林 / 哈里森·福特 / 安娜·德·阿玛斯 / 杰瑞德·莱托',
	'cC': 28,
	'commonSpecial': '感受迷幻末世的荒凉气息',
	'd': '163',
	'dN': '丹尼斯·维伦纽瓦',
	'def': 0,
	'id': 212468,
	'img': 'http://img5.mtime.cn/mt/2017/10/25/095222.65997300_1280X720X2.jpg',
	'is3D': true,
	'isDMAX': true,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': true,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '科幻 / 惊悚',
	'p': [
			'科幻惊悚'
	],
	'preferentialFlag': false,
	'r': 8.2,
	'rc': 0,
	'rd': '20171027',
	'rsC': 0,
	'sC': 118,
	't': '银翼杀手2049',
	'tCn': '银翼杀手2049',
	'tEn': 'Blade Runner 2049',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			},
			{
					'enum': 2,
					'version': '3D'
			},
			{
					'enum': 4,
					'version': 'IMAX3D'
			},
			{
					'enum': 6,
					'version': '中国巨幕'
			}
	],
	'wantedCount': 4973
},
{
	'NearestCinemaCount': 2,
	'NearestDay': 1510819200,
	'NearestShowtimeCount': 2,
	'aN1': '段奕宏',
	'aN2': '江一燕',
	'actors': '段奕宏 / 江一燕 / 杜源 / 郑伟',
	'cC': 39,
	'commonSpecial': '',
	'd': '118',
	'dN': '董越',
	'def': 0,
	'id': 233509,
	'img': 'http://img5.mtime.cn/mt/2017/11/10/094658.58466169_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '剧情 / 悬疑 / 犯罪',
	'p': [
			'剧情悬疑犯罪'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '20171117',
	'rsC': 0,
	'sC': 103,
	't': '暴雪将至',
	'tCn': '暴雪将至',
	'tEn': 'The Looming Storm',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 267
},
{
	'NearestCinemaCount': 10,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 25,
	'aN1': '茱蒂蒙·琼查容苏因',
	'aN2': '查侬·散顶腾古',
	'actors': '茱蒂蒙·琼查容苏因 / 查侬·散顶腾古 / 披纳若·苏潘平佑 / 依莎亚·贺苏汪',
	'cC': 15,
	'commonSpecial': '泰国人把考试作弊拍成了《碟中谍》',
	'd': '130',
	'dN': '纳塔吾·彭皮里亚',
	'def': 0,
	'id': 247578,
	'img': 'http://img5.mtime.cn/mt/2017/10/10/113027.39998023_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': true,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '喜剧 / 犯罪 / 剧情',
	'p': [
			'喜剧犯罪剧情'
	],
	'preferentialFlag': false,
	'r': 8.4,
	'rc': 0,
	'rd': '20171013',
	'rsC': 0,
	'sC': 60,
	't': '天才枪手',
	'tCn': '天才枪手',
	'tEn': 'Bad Genius',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			},
			{
					'enum': 3,
					'version': 'IMAX'
			}
	],
	'wantedCount': 1662
},
{
	'NearestCinemaCount': 16,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 19,
	'aN1': 'Chris Parson',
	'aN2': '辛达·亚当斯',
	'actors': 'Chris Parson / 辛达·亚当斯 / Bob Barlen / 卡尔·布伦克尔',
	'cC': 25,
	'commonSpecial': '父亲为保护家庭隐居丛林',
	'd': '92',
	'dN': 'Jeremy Degruson',
	'def': 0,
	'id': 250337,
	'img': 'http://img5.mtime.cn/mt/2017/09/29/151023.97775917_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '动画 / 喜剧',
	'p': [
			'动画喜剧'
	],
	'preferentialFlag': false,
	'r': 7.5,
	'rc': 0,
	'rd': '20171014',
	'rsC': 0,
	'sC': 54,
	't': '我的爸爸是森林之王',
	'tCn': '我的爸爸是森林之王',
	'tEn': 'The Son of Bigfoot',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 235
},
{
	'NearestCinemaCount': 9,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 14,
	'aN1': '大鹏',
	'aN2': '乔杉',
	'actors': '大鹏 / 乔杉 / 娜扎 / 李鸿其',
	'cC': 12,
	'commonSpecial': '大鹏再组乐队乔杉耍贱娜扎叛逆',
	'd': '119',
	'dN': '大鹏',
	'def': 0,
	'id': 239556,
	'img': 'http://img5.mtime.cn/mt/2017/09/10/112830.94571314_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '喜剧 / 剧情',
	'p': [
			'喜剧剧情'
	],
	'preferentialFlag': false,
	'r': 7.1,
	'rc': 0,
	'rd': '20170929',
	'rsC': 0,
	'sC': 31,
	't': '缝纫机乐队',
	'tCn': '缝纫机乐队',
	'tEn': 'City Of Rock',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 1390
},
{
	'NearestCinemaCount': 8,
	'NearestDay': 1510905600,
	'NearestShowtimeCount': 11,
	'aN1': '狄龙',
	'aN2': '张国荣',
	'actors': '狄龙 / 张国荣 / 周润发 / 李子雄',
	'cC': 8,
	'commonSpecial': '',
	'd': '95',
	'dN': '吴宇森',
	'def': 0,
	'id': 12470,
	'img': 'http://img5.mtime.cn/mt/2017/10/25/114619.38390467_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '惊悚 / 剧情 / 犯罪',
	'p': [
			'惊悚剧情犯罪'
	],
	'preferentialFlag': false,
	'r': 7.9,
	'rc': 0,
	'rd': '20171117',
	'rsC': 0,
	'sC': 13,
	't': '英雄本色',
	'tCn': '英雄本色',
	'tEn': 'A Better Tomorrow',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 10731
},
{
	'NearestCinemaCount': 2,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 2,
	'aN1': '马里奥·卡萨斯',
	'aN2': '芭芭拉·蓝妮',
	'actors': '马里奥·卡萨斯 / 芭芭拉·蓝妮 / 法兰西斯克·欧瑞拉 / 阿娜·瓦格纳',
	'cC': 4,
	'commonSpecial': '剧情反转反转再反转',
	'd': '106',
	'dN': '奥利奥尔·保罗',
	'def': 0,
	'id': 231633,
	'img': 'http://img5.mtime.cn/mt/2017/09/13/115214.76902328_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '犯罪 / 悬疑 / 惊悚',
	'p': [
			'犯罪悬疑惊悚'
	],
	'preferentialFlag': false,
	'r': 8.4,
	'rc': 0,
	'rd': '20170915',
	'rsC': 0,
	'sC': 12,
	't': '看不见的客人',
	'tCn': '看不见的客人',
	'tEn': 'Contratiempo',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 1298
},
{
	'NearestCinemaCount': 3,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 3,
	'aN1': '张美娟',
	'aN2': '赵梦娇',
	'actors': '张美娟 / 赵梦娇 / 陈大刚 / 刘浏',
	'cC': 6,
	'commonSpecial': '',
	'd': '90',
	'dN': '杨广福',
	'def': 0,
	'id': 227588,
	'img': 'http://img31.mtime.cn/mt/2015/11/10/090852.70487756_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '动画 / 冒险 / 喜剧',
	'p': [
			'动画冒险喜剧'
	],
	'preferentialFlag': false,
	'r': 5.6,
	'rc': 0,
	'rd': '20171020',
	'rsC': 0,
	'sC': 10,
	't': '咕噜咕噜美人鱼',
	'tCn': '咕噜咕噜美人鱼',
	'tEn': 'Gulu  Mermaid',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 1006
},
{
	'NearestCinemaCount': 3,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 5,
	'aN1': '成龙',
	'aN2': '皮尔斯·布鲁斯南',
	'actors': '成龙 / 皮尔斯·布鲁斯南 / 刘涛 / 迈克尔·麦克埃尔哈顿',
	'cC': 3,
	'commonSpecial': '成龙化身反恐精英对决皮尔斯南',
	'd': '116',
	'dN': '马丁·坎贝尔',
	'def': 0,
	'id': 226524,
	'img': 'http://img5.mtime.cn/mt/2017/09/15/145930.13207094_1280X720X2.jpg',
	'is3D': true,
	'isDMAX': true,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': true,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '动作 / 惊悚',
	'p': [
			'动作惊悚'
	],
	'preferentialFlag': false,
	'r': 7.4,
	'rc': 0,
	'rd': '20170930',
	'rsC': 0,
	'sC': 6,
	't': '英伦对决',
	'tCn': '英伦对决',
	'tEn': 'The Foreigner',
	'ua': -1,
	'versions': [
			{
					'enum': 2,
					'version': '3D'
			},
			{
					'enum': 4,
					'version': 'IMAX3D'
			},
			{
					'enum': 6,
					'version': '中国巨幕'
			}
	],
	'wantedCount': 5500
},
{
	'NearestCinemaCount': 6,
	'NearestDay': 1511078400,
	'NearestShowtimeCount': 6,
	'aN1': '范伟',
	'aN2': '殷桃',
	'actors': '范伟 / 殷桃 / 张超 / 史依弘',
	'cC': 6,
	'commonSpecial': '',
	'd': '133',
	'dN': '梅峰',
	'def': 0,
	'id': 236840,
	'img': 'http://img5.mtime.cn/mt/2017/10/25/093220.54952707_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '剧情',
	'p': [
			'剧情'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '20171121',
	'rsC': 0,
	'sC': 6,
	't': '不成问题的问题',
	'tCn': '不成问题的问题',
	'tEn': 'Mr.No Problem',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 358
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 5,
	'aN1': '李扬',
	'aN2': '张爱钦',
	'actors': '李扬 / 张爱钦 / 姚晨 / 陈佩斯',
	'cC': 1,
	'commonSpecial': '',
	'd': '88',
	'dN': '速达',
	'def': 0,
	'id': 119498,
	'img': 'http://img31.mtime.cn/mt/2014/07/23/233607.78788556_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '动画 / 奇幻',
	'p': [
			'动画奇幻'
	],
	'preferentialFlag': false,
	'r': 6.2,
	'rc': 0,
	'rd': '20171013',
	'rsC': 0,
	'sC': 5,
	't': '大闹天宫',
	'tCn': '大闹天宫',
	'tEn': 'The Monkey King',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 672
},
{
	'NearestCinemaCount': 5,
	'NearestDay': 1510387200,
	'NearestShowtimeCount': 5,
	'aN1': '葛优',
	'aN2': '刘蓓',
	'actors': '葛优 / 刘蓓 / 冯小刚 / 何冰',
	'cC': 5,
	'commonSpecial': '',
	'd': '90',
	'dN': '冯小刚',
	'def': 0,
	'id': 16755,
	'img': 'http://img31.mtime.cn/mt/2015/03/12/111332.11710337_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '喜剧',
	'p': [
			'喜剧'
	],
	'preferentialFlag': false,
	'r': 7.8,
	'rc': 0,
	'rd': '19971224',
	'rsC': 0,
	'sC': 5,
	't': '甲方乙方',
	'tCn': '甲方乙方',
	'tEn': 'The Dream Factory',
	'ua': -1,
	'versions': [],
	'wantedCount': 367
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 1,
	'aN1': '尚冠武',
	'aN2': '刘琼',
	'actors': '尚冠武 / 刘琼 / 陈燕燕 / 郑君里',
	'cC': 2,
	'commonSpecial': '',
	'd': '0',
	'dN': '朱石麟',
	'def': 0,
	'id': 37957,
	'img': '',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': false,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '剧情',
	'p': [
		'剧情'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '0',
	'rsC': 0,
	'sC': 4,
	't': '艺海风光',
	'tCn': '艺海风光',
	'tEn': 'Vistas of Art',
	'ua': -1,
	'versions': [],
	'wantedCount': 1
},
{
	'NearestCinemaCount': 4,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 4,
	'aN1': '王学圻',
	'aN2': '陈瑾',
	'actors': '王学圻 / 陈瑾 / 白威 / 陈西贝',
	'cC': 4,
	'commonSpecial': '王学圻演绎湘西农民精准扶贫',
	'd': '124',
	'dN': '苗月',
	'def': 0,
	'id': 251038,
	'img': 'http://img5.mtime.cn/mt/2017/09/26/102445.23496629_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '剧情',
	'p': [
		'剧情'
	],
	'preferentialFlag': false,
	'r': 7.3,
	'rc': 0,
	'rd': '20171012',
	'rsC': 0,
	'sC': 4,
	't': '十八洞村',
	'tCn': '十八洞村',
	'tEn': 'Hold Your Hands',
	'ua': -1,
	'versions': [
		{
			'enum': 1,
			'version': '2D'
		}
	],
	'wantedCount': 57
},
{
	'NearestCinemaCount': 2,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 2,
	'aN1': '李川',
	'aN2': '奥密兹·苏查拉特',
	'actors': '李川 / 奥密兹·苏查拉特 / 倪慕斯 / 宋词',
	'cC': 3,
	'commonSpecial': '',
	'd': '0',
	'dN': '李勇昌',
	'def': 0,
	'id': 234673,
	'img': 'http://img5.mtime.cn/mt/2017/09/25/100400.78346942_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '惊悚 / 恐怖',
	'p': [
			'惊悚恐怖'
	],
	'preferentialFlag': false,
	'r': 5.7,
	'rc': 0,
	'rd': '20171012',
	'rsC': 0,
	'sC': 4,
	't': '怨灵2',
	'tCn': '怨灵2',
	'tEn': '',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 80
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 1,
	'aN1': '甄子丹',
	'aN2': '刘德华',
	'actors': '甄子丹 / 刘德华 / 姜皓文 / 郑则仕',
	'cC': 1,
	'commonSpecial': '甄子丹刘德华刀口舔血制霸九龙',
	'd': '128',
	'dN': '王晶',
	'def': 0,
	'id': 225754,
	'img': 'http://img5.mtime.cn/mt/2017/09/15/101130.69230786_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': true,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '动作 / 犯罪',
	'p': [
			'动作犯罪'
	],
	'preferentialFlag': false,
	'r': 7.3,
	'rc': 0,
	'rd': '20170930',
	'rsC': 0,
	'sC': 3,
	't': '追龙',
	'tCn': '追龙',
	'tEn': 'Chasing The Dragon',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			},
			{
					'enum': 6,
					'version': '中国巨幕'
			}
	],
	'wantedCount': 1366
},
{
	'NearestCinemaCount': 3,
	'NearestDay': 1510387200,
	'NearestShowtimeCount': 3,
	'aN1': '王千源',
	'aN2': '秦海璐',
	'actors': '王千源 / 秦海璐 / 张申英 / 田雨',
	'cC': 3,
	'commonSpecial': '',
	'd': '119',
	'dN': '张猛',
	'def': 0,
	'id': 126675,
	'img': 'http://img31.mtime.cn/mt/2016/08/28/132954.38666525_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '喜剧 / 剧情',
	'p': [
			'喜剧剧情'
	],
	'preferentialFlag': false,
	'r': 8,
	'rc': 0,
	'rd': '20110715',
	'rsC': 0,
	'sC': 3,
	't': '钢的琴',
	'tCn': '钢的琴',
	'tEn': 'The Piano in a Factory',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 2439
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 1,
	'aN1': '方力申',
	'aN2': '曾江',
	'actors': '方力申 / 曾江 / 李勤勤 / 李又麟',
	'cC': 1,
	'commonSpecial': '方力申变身打星开启大漠夺宝之旅',
	'd': '95',
	'dN': '杨健',
	'def': 0,
	'id': 250629,
	'img': 'http://img5.mtime.cn/mt/2017/10/27/100305.19753916_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '动作 / 喜剧',
	'p': [
			'动作喜剧'
	],
	'preferentialFlag': false,
	'r': 5.5,
	'rc': 0,
	'rd': '20171103',
	'rsC': 0,
	'sC': 2,
	't': '宝贝特攻',
	'tCn': '宝贝特攻',
	'tEn': 'Baby Task Group',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 42
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 1,
	'aN1': '古天乐',
	'aN2': '张智霖',
	'actors': '古天乐 / 张智霖 / 林家栋 / 蔡卓妍',
	'cC': 2,
	'commonSpecial': '古天乐饰演灵魂警探',
	'd': '90',
	'dN': '邱礼涛',
	'def': 0,
	'id': 240236,
	'img': 'http://img5.mtime.cn/mt/2017/09/22/160049.76079497_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '惊悚 / 恐怖',
	'p': [
			'惊悚恐怖'
	],
	'preferentialFlag': false,
	'r': 5.5,
	'rc': 0,
	'rd': '20171027',
	'rsC': 0,
	'sC': 2,
	't': '常在你左右',
	'tCn': '常在你左右',
	'tEn': 'Accompany You',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 677
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510387200,
	'NearestShowtimeCount': 1,
	'aN1': '白恩',
	'aN2': '吕星辰',
	'actors': '白恩 / 吕星辰 / 赫子铭 / 王璐',
	'cC': 1,
	'commonSpecial': '再现送淞沪会战六百壮士悲歌',
	'd': '109',
	'dN': '廖希',
	'def': 0,
	'id': 250625,
	'img': 'http://img5.mtime.cn/mt/2017/09/07/114359.85438056_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '剧情',
	'p': [
			'剧情'
	],
	'preferentialFlag': false,
	'r': 6.8,
	'rc': 0,
	'rd': '20170922',
	'rsC': 0,
	'sC': 2,
	't': '捍卫者',
	'tCn': '捍卫者',
	'tEn': 'Defenders',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 184
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510387200,
	'NearestShowtimeCount': 1,
	'aN1': '卡西·阿弗莱克',
	'aN2': '卢卡斯·赫奇斯',
	'actors': '卡西·阿弗莱克 / 卢卡斯·赫奇斯 / 米歇尔·威廉姆斯 / 凯尔·钱德勒',
	'cC': 1,
	'commonSpecial': '卡西阿弗莱克奥斯卡封帝之作',
	'd': '135',
	'dN': '肯尼斯·罗纳根',
	'def': 0,
	'id': 220423,
	'img': 'http://img5.mtime.cn/mt/2017/08/09/101245.62138995_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '剧情',
	'p': [
			'剧情'
	],
	'preferentialFlag': false,
	'r': 8,
	'rc': 0,
	'rd': '20170825',
	'rsC': 0,
	'sC': 1,
	't': '海边的曼彻斯特',
	'tCn': '海边的曼彻斯特',
	'tEn': 'Manchester by the Sea',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 1413
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510387200,
	'NearestShowtimeCount': 1,
	'aN1': '树锋',
	'aN2': '味芳',
	'actors': '树锋 / 味芳 / 赵青 / 冯都',
	'cC': 1,
	'commonSpecial': '',
	'd': '78',
	'dN': '赵青',
	'def': 0,
	'id': 251439,
	'img': 'http://img5.mtime.cn/mt/2017/10/26/113001.89203352_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': false,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '纪录片',
	'p': [
			'纪录片'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '20171117',
	'rsC': 0,
	'sC': 1,
	't': '我只认识你',
	'tCn': '我只认识你',
	'tEn': 'Please Remember Me',
	'ua': -1,
	'versions': [],
	'wantedCount': 5
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510473600,
	'NearestShowtimeCount': 1,
	'aN1': '吴京',
	'aN2': '弗兰克·格里罗',
	'actors': '吴京 / 弗兰克·格里罗 / 吴刚 / 张翰',
	'cC': 1,
	'commonSpecial': '吴京领衔坦克版速度与激情',
	'd': '123',
	'dN': '吴京',
	'def': 0,
	'id': 229733,
	'img': 'http://img5.mtime.cn/mt/2017/07/21/162643.51070350_1280X720X2.jpg',
	'is3D': true,
	'isDMAX': true,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': true,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '动作 / 战争',
	'p': [
			'动作战争'
	],
	'preferentialFlag': false,
	'r': 7.3,
	'rc': 0,
	'rd': '20170727',
	'rsC': 0,
	'sC': 1,
	't': '战狼2',
	'tCn': '战狼2',
	'tEn': 'Wolf Warriors Ⅱ',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			},
			{
					'enum': 2,
					'version': '3D'
			},
			{
					'enum': 3,
					'version': 'IMAX'
			},
			{
					'enum': 6,
					'version': '中国巨幕'
			}
	],
	'wantedCount': 9199
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510473600,
	'NearestShowtimeCount': 1,
	'aN1': '白杨',
	'aN2': '陶金',
	'actors': '白杨 / 陶金 / 上官云珠 / 舒绣文',
	'cC': 1,
	'commonSpecial': '',
	'd': '210',
	'dN': '蔡楚生',
	'def': 0,
	'id': 26069,
	'img': 'http://img31.mtime.cn/mt/2014/02/23/014717.93272959_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': false,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '剧情',
	'p': [
			'剧情'
	],
	'preferentialFlag': false,
	'r': 8.5,
	'rc': 0,
	'rd': '20171027',
	'rsC': 0,
	'sC': 1,
	't': '一江春水向东流',
	'tCn': '一江春水向东流',
	'tEn': 'A Spring River Flows East',
	'ua': -1,
	'versions': [],
	'wantedCount': 113
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510473600,
	'NearestShowtimeCount': 1,
	'aN1': '涂们',
	'aN2': '王超北',
	'actors': '涂们 / 王超北 / 阿拉腾乌拉 / 伊丹纳',
	'cC': 1,
	'commonSpecial': '',
	'd': '110',
	'dN': '周子阳',
	'def': 0,
	'id': 235158,
	'img': 'http://img5.mtime.cn/mt/2017/07/28/174333.67528647_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '剧情',
	'p': [
			'剧情'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '0',
	'rsC': 0,
	'sC': 1,
	't': '老兽',
	'tCn': '老兽',
	'tEn': 'Old Beast',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 8
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1511337600,
	'NearestShowtimeCount': 1,
	'aN1': '姜武',
	'aN2': '宋洋',
	'actors': '姜武 / 宋洋 / 袁文康 / 谭卓',
	'cC': 1,
	'commonSpecial': '',
	'd': '119',
	'dN': '忻钰坤',
	'def': 0,
	'id': 234616,
	'img': 'http://img5.mtime.cn/mt/2017/11/06/100852.70095222_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '犯罪 / 悬疑 / 动作',
	'p': [
			'犯罪悬疑动作'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '0',
	'rsC': 0,
	'sC': 1,
	't': '暴裂无声',
	'tCn': '暴裂无声',
	'tEn': 'Wrath Of Silence',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 202
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 1,
	'aN1': '范逸臣',
	'aN2': '黄奕',
	'actors': '范逸臣 / 黄奕 / 沈梦辰 / 韩承羽',
	'cC': 2,
	'commonSpecial': '',
	'd': '103',
	'dN': '刘欣翰',
	'def': 0,
	'id': 251237,
	'img': 'http://img5.mtime.cn/mt/2017/10/16/183051.76737649_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': false,
	'm': '',
	'movieType': '剧情 / 爱情',
	'p': [
			'剧情爱情'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '20171103',
	'rsC': 0,
	'sC': 2,
	't': '识色，幸也',
	'tCn': '识色，幸也',
	'tEn': '',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 37
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 1,
	'aN1': '王骁',
	'aN2': '姜瑞佳',
	'actors': '王骁 / 姜瑞佳 / 吴刚 / 高云翔',
	'cC': 1,
	'commonSpecial': '',
	'd': '96',
	'dN': '沈东',
	'def': 0,
	'id': 250874,
	'img': 'http://img5.mtime.cn/mt/2017/09/26/101658.42137777_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': false,
	'm': '',
	'movieType': '爱情 / 剧情',
	'p': [
			'爱情剧情'
	],
	'preferentialFlag': false,
	'r': 6.8,
	'rc': 0,
	'rd': '20171017',
	'rsC': 0,
	'sC': 1,
	't': '六年，六天',
	'tCn': '六年，六天',
	'tEn': 'Six Years,Six Days',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 36
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510300800,
	'NearestShowtimeCount': 1,
	'aN1': '保剑锋',
	'aN2': '隋源',
	'actors': '保剑锋 / 隋源 / 孙茜 / 刘抒鹃',
	'cC': 1,
	'commonSpecial': '',
	'd': '94',
	'dN': '刘抒鹃',
	'def': 0,
	'id': 249488,
	'img': 'http://img5.mtime.cn/mt/2017/09/27/100454.81878486_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': false,
	'm': '',
	'movieType': '剧情',
	'p': [
			'剧情'
	],
	'preferentialFlag': false,
	'r': 6.7,
	'rc': 0,
	'rd': '20171017',
	'rsC': 0,
	'sC': 1,
	't': '你若安好',
	'tCn': '你若安好',
	'tEn': "Doctor's Mind",
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 36
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510387200,
	'NearestShowtimeCount': 1,
	'aN1': '乔瑟夫·哈德',
	'aN2': '芭芭拉·苏科瓦',
	'actors': '乔瑟夫·哈德 / 芭芭拉·苏科瓦 / 莱恩·库德里亚维斯基 / Nicolau Breyner',
	'cC': 1,
	'commonSpecial': '',
	'd': '106',
	'dN': '玛丽亚·丝奇拉德',
	'def': 0,
	'id': 228351,
	'img': 'http://img31.mtime.cn/mt/2016/06/03/144936.19065898_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': false,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': false,
	'm': '',
	'movieType': '剧情',
	'p': [
			'剧情'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '0',
	'rsC': 0,
	'sC': 1,
	't': '黎明之前',
	'tCn': '黎明之前',
	'tEn': 'Stefan Zweig: Farewell to Europe',
	'ua': -1,
	'versions': [],
	'wantedCount': 0
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510387200,
	'NearestShowtimeCount': 1,
	'aN1': '布鲁诺·甘茨',
	'aN2': '亚历山大·斐林',
	'actors': '布鲁诺·甘茨 / 亚历山大·斐林 / 西尔维斯特·格洛斯 / Pit Bukowski',
	'cC': 1,
	'commonSpecial': '',
	'd': '100',
	'dN': '马蒂·吉斯切内克',
	'def': 0,
	'id': 239406,
	'img': 'http://img5.mtime.cn/mt/2017/10/25/160551.65382646_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': false,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': false,
	'm': '',
	'movieType': '喜剧 / 剧情',
	'p': [
			'喜剧剧情'
	],
	'preferentialFlag': false,
	'r': 0,
	'rc': 0,
	'rd': '20170601',
	'rsC': 0,
	'sC': 1,
	't': '光芒渐逝的年代',
	'tCn': '光芒渐逝的年代',
	'tEn': 'In Zeiten des abnehmenden Lichts',
	'ua': -1,
	'versions': [],
	'wantedCount': 2
},
{
	'NearestCinemaCount': 1,
	'NearestDay': 1510473600,
	'NearestShowtimeCount': 1,
	'aN1': '陈都灵',
	'aN2': '林柏宏',
	'actors': '陈都灵 / 林柏宏 / 汪铎 / 郝劭文',
	'cC': 1,
	'commonSpecial': '',
	'd': '0',
	'dN': '张天辉',
	'def': 0,
	'id': 247317,
	'img': 'http://img5.mtime.cn/mt/2017/10/16/161441.82575720_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': false,
	'm': '',
	'movieType': '悬疑',
	'p': [
			'悬疑'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '20171124',
	'rsC': 0,
	'sC': 1,
	't': '推理笔记',
	'tCn': '推理笔记',
	'tEn': 'Inference Notes',
	'ua': -1,
	'versions': [
			{
					'enum': 1,
					'version': '2D'
			}
	],
	'wantedCount': 370
},
{
	'NearestCinemaCount': 6,
	'NearestDay': 1510905600,
	'NearestShowtimeCount': 20,
	'aN1': '凯蒂·萨瓦',
	'aN2': '凯瑟琳·希金斯',
	'actors': '凯蒂·萨瓦 / 凯瑟琳·希金斯 / 陈钰芸 / 李依馨',
	'cC': 6,
	'commonSpecial': '',
	'd': '87',
	'dN': '司徒永华',
	'def': 0,
	'id': 231375,
	'img': 'http://img5.mtime.cn/mt/2017/11/07/162610.21197732_1280X720X2.jpg',
	'is3D': false,
	'isDMAX': false,
	'isFilter': false,
	'isHasTrailer': true,
	'isHot': false,
	'isIMAX': false,
	'isIMAX3D': false,
	'isNew': false,
	'isTicket': true,
	'm': '',
	'movieType': '恐怖',
	'p': [
			'恐怖'
	],
	'preferentialFlag': false,
	'r': -1,
	'rc': 0,
	'rd': '20171117',
	'rsC': 0,
	'sC': 24,
	't': '深宫怨灵',
	'tCn': '深宫怨灵',
	'tEn': 'Palace of the Damned',
	'ua': -1,
	'versions': [],
	'wantedCount': 31
}
],
'totalComingMovie': 63,
};

export default movies;