export const GETHOTPLAYMOVIES = 'MOVIES/GETHOTPLAYMOVIES';
export const GETHOTPLAYMOVIES_SUCCESS = 'MOVIES/GETHOTPLAYMOVIES_SUCCESS';
export const GETHOTPLAYMOVIES_FAIL = 'MOVIES/GETHOTPLAYMOVIES_FAIL';

export const GETCOMINGNEWMOVIES = 'MOVIES/GETCOMINGNEWMOVIES';
export const GETCOMINGNEWMOVIES_SUCCESS = 'MOVIES/GETCOMINGNEWMOVIES_SUCCESS';
export const GETCOMINGNEWMOVIES_FAIL = 'MOVIES/GETCOMINGNEWMOVIES_FAIL';
